/*
 * l293d_hw.h
 *
 *  Created on: 9 sie 2022
 *      Author: Michal Klebokowski
 */

#ifndef L293D_L293D_HW_H_
#define L293D_L293D_HW_H_

//
// L239D MOTOR ENABLE (MOTOR DIRECRION) PINS DEFINITIONS
//

//FRONT LEFT MOTOR
#define FL_ENABLE1_DIR_REG	DDRA
#define FL_ENABLE1_SET_REG	PORTA
#define FL_ENABLE1_PIN 		(1<<PA2)
#define FL_ENABLE2_DIR_REG 	DDRA
#define FL_ENABLE2_SET_REG	PORTA
#define FL_ENABLE2_PIN		(1<<PA3)

//FRONT RIGHT MOTOR
#define FR_ENABLE1_DIR_REG	DDRA
#define FR_ENABLE1_SET_REG	PORTA
#define FR_ENABLE1_PIN		(1<<PA4)
#define FR_ENABLE2_DIR_REG	DDRA
#define FR_ENABLE2_SET_REG	PORTA
#define FR_ENABLE2_PIN		(1<<PA5)

//REAR LEFT MOTOR
#define RL_ENABLE1_DIR_REG	DDRA
#define RL_ENABLE1_SET_REG	PORTA
#define RL_ENABLE1_PIN		(1<<PA6)
#define RL_ENABLE2_DIR_REG	DDRA
#define RL_ENABLE2_SET_REG	PORTA
#define RL_ENABLE2_PIN		(1<<PA7)

//REAR RIGHT MOTOR
#define RR_ENABLE1_DIR_REG	DDRC
#define RR_ENABLE1_SET_REG	PORTC
#define RR_ENABLE1_PIN		(1<<PC7)
#define RR_ENABLE2_DIR_REG	DDRC
#define RR_ENABLE2_SET_REG	PORTC
#define RR_ENABLE2_PIN		(1<<PC6)

//
// PWM DEFINITIONS
//

// FRONT LEFT MOTOR
#define FL_PWM_DIR_REG DDRH
#define FL_PWM_PIN (1<<PH3)
#define FL_PWM_REGISTER OCR4A

//FRONT RIGHT MOTOR
#define FR_PWM_DIR_REG DDRH
#define FR_PWM_PIN (1<<PH4)
#define FR_PWM_REGISTER OCR4B

// REAR LEFT MOTOR
#define RL_PWM_DIR_REG DDRB
#define RL_PWM_PIN (1<<PB5)
#define RL_PWM_REGISTER OCR1A

// REAR RIGHT MOTOR
#define RR_PWM_DIR_REG DDRB
#define RR_PWM_PIN (1<<PB6)
#define RR_PWM_REGISTER OCR1B

//
//	SET DIRECTION MACROS
//

// *** FRONT LEFT MOTOR MACROS ***
#define FL_FORWARD	FL_ENABLE1_SET_REG |= FL_ENABLE1_PIN; \
					FL_ENABLE2_SET_REG &= ~FL_ENABLE2_PIN


#define FL_BACKWARD FL_ENABLE2_SET_REG |= FL_ENABLE2_PIN; \
					FL_ENABLE1_SET_REG &= ~FL_ENABLE1_PIN

#define FL_STOP 	FL_ENABLE2_SET_REG &= ~FL_ENABLE2_PIN; \
					FL_ENABLE1_SET_REG &= ~FL_ENABLE1_PIN

// *** FRONT RIGHT MOTOR MACROS ***
#define FR_FORWARD 	FR_ENABLE1_SET_REG |= FR_ENABLE1_PIN; \
					FR_ENABLE2_SET_REG &= ~FR_ENABLE2_PIN

#define FR_BACKWARD FR_ENABLE2_SET_REG |= FR_ENABLE2_PIN; \
					FR_ENABLE1_SET_REG &= ~FR_ENABLE1_PIN

#define FR_STOP 	FR_ENABLE2_SET_REG &= ~FR_ENABLE2_PIN; \
					FR_ENABLE1_SET_REG &= ~FR_ENABLE1_PIN

// *** REAR LEFT MOTOR MACROS ***
#define RL_FORWARD	RL_ENABLE1_SET_REG |= RL_ENABLE1_PIN; \
					RL_ENABLE2_SET_REG &= ~RL_ENABLE2_PIN

#define RL_BACKWARD	RL_ENABLE2_SET_REG |= RL_ENABLE2_PIN; \
					RL_ENABLE1_SET_REG &= ~RL_ENABLE1_PIN

#define RL_STOP 	RL_ENABLE2_SET_REG &= ~RL_ENABLE2_PIN; \
					RL_ENABLE1_SET_REG &= ~RL_ENABLE1_PIN

// *** REAR RIGHT MOTOR MACROS ***
#define RR_FORWARD 	RR_ENABLE1_SET_REG |= RR_ENABLE1_PIN; \
					RR_ENABLE2_SET_REG &= ~RR_ENABLE2_PIN

#define RR_BACKWARD	RR_ENABLE2_SET_REG |= RR_ENABLE2_PIN; \
					RR_ENABLE1_SET_REG &= ~RR_ENABLE1_PIN

#define RR_STOP 	RR_ENABLE2_SET_REG &= ~RR_ENABLE2_PIN; \
					RR_ENABLE1_SET_REG &= ~RR_ENABLE1_PIN

//
//	FUNCTIONS
//

void HW_Timer1InitPWM(uint8_t InitialFill);		//Initialization - Setting Timer 0 in Fast PWM mode
void HW_Timer4InitPWM(uint8_t InitialFill);		//Initialization - Setting Timer 1 in Fast PWM mode
void HW_MotorDirPinsInit(void);					//Pins initialization

#endif /* L293D_L293D_HW_H_ */
